### ISSUE TITLE
simple rule of resetting delta doesn't work

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-phi-normalizer#504]
My YAML file:

```yaml
title: "simple"
rules:
  - name: simple
    description: 'change 33 double to 42 double'
    pattern: |
      Δ ⤍ 40-40-80-00-00-00-00-00
    result: |
      Δ ⤍ 40-45-00-00-00-00-00-00
    when: [ ]
    tests: [ ]
```

I'm getting:

```
$ normalizer transform --rules /hone/simple.yml /target/generated-sources/phi/Hello.phi --single -o /target/generated-sources/phi-optimized/Hello.phi
>> normalizer: syntax error at line 1, column 1 before `Δ'
>> on input
>> Δ ⤍ 40-40-80-00-00-00-00-00
```

What's wrong?

PS. I tried this, same result (added brackets):

```yaml
title: "simple"
rules:
  - name: simple
    description: 'change 33 double to 42 double'
    pattern: |
      (Δ ⤍ 40-40-80-00-00-00-00-00)
    result: |
      (Δ ⤍ 40-45-00-00-00-00-00-00)
    when: [ ]
    tests: [ ]
```

**Comment by yegor256** [comment]
@deemp please, help

**Comment by yegor256** [comment]
@deemp I also tried this, same result:

```
title: "simple"
rules:
  - name: simple
    description: test
    pattern: |
      a ↦ ⟦⟧.b
    result: |
      a ↦ b
    when: [ ]
    tests: [ ]
```

What am I doing wrong?
