### ISSUE TITLE
why tests.output is an array, in YAML for rules?

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-phi-normalizer#585]
I see this, in `new.yaml`:

```
  - name: VOID
    description: 'Void attribute access'
    pattern: |
      ⟦ !τ ↦ ∅, !B ⟧.!τ
    result: |
      ⊥
    when: []
    tests:
      - name: Phi Paper Example E2 second dispatch
        input: '⟦ x ↦ ξ.t, t ↦ ∅ ⟧.t(ρ ↦ ⟦ x ↦ ξ.t, t ↦ ∅ ⟧)'
        output: ['⊥(ρ ↦ ⟦ x ↦ ξ.t, t ↦ ∅ ⟧)']

```

Why `output` has an array? Is there a possibility to get two or more different outputs from a single input? If not, I suggest making the value of `output` a scalar (one single value).
