### ISSUE TITLE
rewriting stopped working after the introduction of syntax sugar

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-phi-normalizer#680]
This is my `rule.yml`:

```yaml
title: "simple"
rules:
  - name: simple
    description: 'change 7777 int to 5555 int'
    pattern: |
      Φ.org.eolang.bytes ( α0 ↦ ⟦ Δ ⤍ 00-00-00-00-00-00-1E-61 ⟧ )
    result: |
      Φ.org.eolang.bytes ( α0 ↦ ⟦ Δ ⤍ 40-B5-B3-00-00-00-15-B3 ⟧ )
    when: [ ]
    tests: [ ]
```

This is what I'm doing:

```
$ cat bar.phi
{⟦
  x ↦ Φ.foo(
    Φ.jeo.int(7777)
  )
⟧}
$ eo-phi-normalizer rewrite -r rule.yml bar.phi
simple
Input:
{
  ⟦
    x ↦ Φ.foo(
      Φ.jeo.int(
        7777
      )
    )
  ⟧
}
====================================================
Result 1 out of 1:
{
  ⟦
    x ↦ Φ.foo(
      Φ.jeo.int(
        7777
      )
    )
  ⟧
}
----------------------------------------------------
```

I expect 7777 to be replaced with 5555.

Rewriting works just fine for this input:

```
{⟦
  x ↦ Φ.foo(
    Φ.jeo.int(Φ.org.eolang.number(Φ.org.eolang.bytes ( α0 ↦ ⟦ Δ ⤍ 00-00-00-00-00-00-1E-61 ⟧ )))
  )
⟧}
```

**Comment by yegor256** [comment]
@deemp please, help

**Comment by deemp** [comment]
@yegor256, I don't yet know the particular reason for this behavior. Perhaps it's because some literals are desugared not immediately after parsing, and some pattern-matching fails. I'll investigate.

**Comment by yegor256** [comment]
@deemp any update on this? It's a blocker for us :(

**Comment by yegor256** [comment]
@deemp here is a bigger experiment:

```
{⟦
  x ↦ Φ.foo(
    Φ.org.eolang.bytes ( α0 ↦ ⟦ Δ ⤍ 00-00-00-00-00-00-1E-61 ⟧ )
  ),
  y ↦ Φ.foo(7777)
⟧}
```

The rule file is this:

```
title: "simple"
rules:
  - name: simple
    description: 'change 7777 int to 5555 int'
    pattern: |
      Φ.org.eolang.bytes ( α0 ↦ ⟦ Δ ⤍ 00-00-00-00-00-00-1E-61 ⟧ )
    result: |
      Φ.org.eolang.bytes ( α0 ↦ ⟦ Δ ⤍ 40-B5-B3-00-00-00-15-B3 ⟧ )
  - name: second
    description: 'change 7777 int to 5555 int'
    pattern: |
      Φ.foo(7777)
    result: |
      Φ.foo(5555)
```

I'm getting:

```
$ eo-phi-normalizer rewrite --rules rule.yml bar.phi --single
{
  ⟦
    x ↦ Φ.foo(
      Φ̇.bytes(
        ⟦
          Δ ⤍ 40-B5-B3-00-00-00-15-B3
        ⟧
      )
    ),
    y ↦ Φ.foo(
      7777
    )
  ⟧
}
```

The first rule applies, while the second one doesn't.
